### ISSUE TITLE
xpra not working - am I missing something?

### ISSUE THREAD

**Issue by mascip** [rogaha/docker-desktop#19]
Hi, for a start I'm trying to use docker-desktop locally on my PC. I follow your instructions and when I do:

```
xpra --ssh="ssh -p 49153" attach ssh:docker@192.168.56.102:10 
```

I get this output:

```
docker@172.17.42.1's password:   
bash: .xpra/run-xpra: No such file or directory   
Connection lost
```

I have xpra installed but I have never used it, so I might be missing something.

However, this works:

```
ssh docker@172.17.42.1 -p 49153 firefox
```

and it fact it's kind of enough for me. What are the benefits of xpra over simple ssh?

**Comment by mskonovalov** [comment]
I've got the same problem

2015-03-14 11:04:49,023 error on publisher AvahiPublisher(Xpra ssh :10 :22 interface=-1)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/xpra/net/avahi_publisher.py", line 77, in start
    publisher.start()
  File "/usr/lib/python2.7/dist-packages/xpra/net/avahi_publisher.py", line 118, in start
    bus = dbus.SystemBus()
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 194, in __new__
    private=private)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
DBusException: org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
2015-03-14 11:04:49,025 error on publisher AvahiPublisher(Xpra ssh :10 :22 interface=-1): org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
